run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - stylecheck

linters-settings:
  goimports:
    local-prefixes: github.com/danmurf/datakeg
  revive:
    confidence: 0.8
  stylecheck:
    checks: ["all", "-ST1000"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
